#!/usr/bin/env bash

RELEASE="master"
DOWNLOAD="https://github.com/jpolo/laptop/archive/$RELEASE.tar.gz"
PACKAGE_NAME=ansible-playbook-laptop
PACKAGE_ARCHIVE="$PACKAGE_NAME.tar.gz"
TMPDIR="{${TMPDIR:-$(dirname $(mktemp))/}"

set -e

echo '==================================='
echo 'Laptop installer'
echo '==================================='
echo

# Remove old laptop playbook
if [[ ! -x $TMPDIR/$PACKAGE_ARCHIVE ]]; then
	echo "[Info] Remove $PACKAGE_NAME playbook"
	rm -rf $TMPDIR$PACKAGE_NAME*
fi


# Download and run laptop playbook
echo "[Info] Download $PACKAGE_NAME playbook"
cd $TMPDIR
curl -fsSL -o $PACKAGE_ARCHIVE $DOWNLOAD
mkdir $TMPDIR$PACKAGE_NAME
tar -zxf $PACKAGE_ARCHIVE --directory $TMPDIR$PACKAGE_NAME --strip-components=1

# Modify the PATH
# This should be subsequently updated in shell settings
export PATH=/usr/local/bin:$PATH


echo "[Info] Run $PACKAGE_NAME playbook"
cd $TMPDIR$PACKAGE_NAME
$TMPDIR$PACKAGE_NAME/scripts/play

