#!/usr/bin/env zsh
#⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
# ZSH startup script : custom personal config
#
# 📝 This file can be modified and will never be overwritten by installation scripts
#⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

# Plugin modules belong in $ZIM_CONFIG_FILE, not this runtime config file.
# Add modules with zmodule, for example:
#
# zmodule ohmyzsh/ohmyzsh --root plugins/common-aliases
# zmodule ohmyzsh/ohmyzsh --root plugins/git
# zmodule ohmyzsh/ohmyzsh --root plugins/bundler
# zmodule ohmyzsh/ohmyzsh --root plugins/ruby
# zmodule ohmyzsh/ohmyzsh --root plugins/rails

# Be careful with dotenv plugins because they execute project environment files.
