#!/usr/bin/env zsh
#⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
# ZSH startup script : custom personal config
#
# 📝 This file can be modified and will never be overwritten by installation scripts
#⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

# Examples of common plugins
# ⬇ Uncomment one of these line will install the plugin
#
# zinit snippet OMZP::common-aliases
# zinit snippet OMZP::git
# zinit snippet OMZP::bundler
# zinit snippet OMZP::git
# zinit snippet OMZP::ruby
# zinit snippet OMZP::rails

# 🟠 DO NOT ENABLE zinit snippet OMZP::dotenv
