#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$0")"
source "$SCRIPT_DIR/_functions.sh"
cd "$SCRIPT_DIR/.."
ROOT_DIR=$(pwd)

CONFIG_DIR="$ROOT_DIR/etc"
TEST_DIR="$ROOT_DIR/tests"
ROLE_DIR="$ROOT_DIR/roles"
COLLECTION_DIR="$ROOT_DIR/collections"

export ANSIBLE_COLLECTIONS_PATHS="$ANSIBLE_COLLECTIONS_PATHS:$COLLECTION_DIR"
export ANSIBLE_ROLES_PATH="$ANSIBLE_ROLES_PATH:$ROLE_DIR"

# Install ansible
install_ansible

# Install local roles
#mkdir -p $ROLE_TARGET_DIR
#cp -a $ROLE_DIR/. $ROLE_TARGET_DIR

# Install dependencies
ansible-galaxy collection install -r $CONFIG_DIR/requirements.yml -p "$COLLECTION_DIR"
ansible-playbook -i $CONFIG_DIR/inventory $CONFIG_DIR/main.yml --ask-become-pass $@
