#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
source "$SCRIPT_DIR/_stdlib.sh"
source "$SCRIPT_DIR/_env.sh"

# ✗ En local, ce script ne doit pas être executé
# ✓ Sur Scalingo, ce script doit être executé par le Procfile
# ✓ Sur GCP, ce script doit être executé par Cloud build (pas le Procfile)

# Migrate database
puts_step 'Migrate database'
if [[ "$RAILS_ENV" = "development" ]];then
  bundle exec rake db:create
fi
bundle exec rake db:migrate

