typeset -A ZINIT

## Functions
_zsh-zinit-install () {
  ZINIT_HOME=$XDG_CACHE_HOME/zsh/zinit
  ZINIT[HOME_DIR]=$ZINIT_HOME
  ZINIT[ZCOMPDUMP_PATH]=$XDG_CACHE_HOME/zsh/zcompdump

  if [[ ! -f $ZINIT_HOME/bin/zinit.zsh ]]; then
    git clone https://github.com/zdharma-continuum/zinit $ZINIT_HOME/bin
    zcompile $ZINIT_HOME/bin/zinit.zsh
  fi

  if [[ -f "$ZINIT_HOME/bin/zinit.zsh" ]];then
    source $ZINIT_HOME/bin/zinit.zsh
  else
    echo "zinit cannot be installed"
  fi;
}

_zsh-load-plugins () {
  local directory=$1
  ## Load everything in .zshrc.d/
  if [[ -d "$directory/" ]]; then
    for i in $(find "$directory/" -maxdepth 1 -type f -name "*.sh");
    do
      . $i;
    done
  fi
}

## Launch
_zsh-zinit-install
_zsh-load-plugins "$HOME/.zshrc.d"
if [ ! -z "$XDG_DATA_HOME" ]; then
  _zsh-load-plugins "$XDG_DATA_HOME/zsh"
fi
