name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  validate:
    runs-on: macOS-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: ⚙️ Setup
      uses: w5s/actions/setup@f43e3ab61de5e8f1471ed61d184fc5b67ab9c2af # main

    - name: ⚙️ Setup tools
      run: |
        brew install coreutils

    - name: ⚙️ Project Setup
      uses: w5s/actions/task@f43e3ab61de5e8f1471ed61d184fc5b67ab9c2af # main
      with:
        task: setup

    - name: 🔍 Validate
      uses: w5s/actions/task@f43e3ab61de5e8f1471ed61d184fc5b67ab9c2af # main
      with:
        task: validate
      env:
        TEST_TMP_DIR: "${{ runner.temp }}"


