name: CI

on:
  push:
    branches:
      - main
  merge_group: {}

permissions:
  actions: read
  contents: read

jobs:
  validate:
    runs-on: macOS-latest

    steps:
    - name: ⬇️ Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: ⚙️ Setup
      uses: w5s/actions/setup@508116754f59434fb4d3b809d928bbfd0fb39410 # main

    - name: ⚙️ Setup tools
      run: |
        brew install coreutils

    - name: ⚙️ Project Setup
      uses: w5s/actions/task@508116754f59434fb4d3b809d928bbfd0fb39410 # main
      with:
        task: setup

    - name: 🔍 Validate
      uses: w5s/actions/task@508116754f59434fb4d3b809d928bbfd0fb39410 # main
      with:
        task: validate
      env:
        TEST_TMP_DIR: "${{ runner.temp }}"


